import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SayHello } from "./page";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-red-500 flex space-x-4">
            <div>
              <Link href={'/'}>
            Navbar
            </Link>
              
            </div>
            <Link href={'/cond-rendering'}>
            conditional Rendering
            </Link>
        </div>
        {children}
        
      </body>
    </html>
  );
}
